# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 0945a5705b8f
Revises: 08d11df0a194
Create Date: 2021-06-24 15:46:44.018561

"""

# revision identifiers, used by Alembic.
revision = '0945a5705b8f'
down_revision = '08d11df0a194'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE typeplan RENAME TO typesubscription")
    op.add_column('billing_subscriptions', sa.Column('stripe_product_id', sa.String(length=100), nullable=True))
    op.add_column('billing_subscriptions', sa.Column('type', sa.Enum(
        'USAGE_BASED', 'USAGE_TRIAL', 'USAGE_UNLIMITED', name='typesubscription'), default='USAGE_BASED'))
    op.drop_constraint('billing_subscriptions_plan_id_fkey', 'billing_subscriptions', type_='foreignkey')
    op.drop_column('billing_subscriptions', 'plan_id')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('USAGE_BASED', 'USAGE_TRIAL', 'USAGE_UNLIMITED', name='typeplan'), autoincrement=False, nullable=False),
    sa.Column('number_of_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stripe_product_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='billing_plans_pkey')
    )
    op.add_column('billing_subscriptions', sa.Column(
        'plan_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('billing_subscriptions_plan_id_fkey',
                          'billing_subscriptions', 'billing_plans', ['plan_id'], ['id'])
    op.drop_column('billing_subscriptions', 'type')
    op.drop_column('billing_subscriptions', 'stripe_product_id')
    op.execute("DROP TYPE typesubscription")
    # ### end Alembic commands ###
