# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 502f33370459
Revises: 3f058914f241
Create Date: 2021-06-09 14:59:31.941302

"""

# revision identifiers, used by Alembic.
revision = '502f33370459'
down_revision = '3f058914f241'

from alembic import op

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE typeplan ADD VALUE 'USAGE_UNLIMITED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE typeplan RENAME TO typeplan_old")
    op.execute(
        "CREATE TYPE typeplan AS ENUM('USAGE_BASED', 'USAGE_TRIAL')")
    op.execute((
        "ALTER TABLE billing_plans ALTER COLUMN type TYPE typeplan USING "
        "type::text::typeplan"
    ))
    op.execute("DROP TYPE typeplan_old")
    # ### end Alembic commands ###
