# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 72f5028372d2
Revises: f9a30386bd74
Create Date: 2020-05-09 16:53:54.402905

"""

# revision identifiers, used by Alembic.
revision = '72f5028372d2'
down_revision = 'f9a30386bd74'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_connect_info', sa.Column('company', sa.String(length=100), nullable=True))
    op.add_column('linkedin_connect_info', sa.Column('education', sa.String(length=100), nullable=True))
    op.add_column('linkedin_connect_info', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_connect_info', 'location')
    op.drop_column('linkedin_connect_info', 'education')
    op.drop_column('linkedin_connect_info', 'company')
    # ### end Alembic commands ###
