# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 914a471b3f7e
Revises: 1120c48d298f
Create Date: 2020-06-12 16:25:26.385665

"""

# revision identifiers, used by Alembic.
revision = '914a471b3f7e'
down_revision = '1120c48d298f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'dashboards', ['uuid'])
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('UPDATE dashboards SET uuid = uuid_generate_v4() WHERE 1 = 1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dashboards_uuid_key', 'dashboards', type_='unique')
    op.drop_column('dashboards', 'uuid')
    # ### end Alembic commands ###
