# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: d4415b11be73
Revises: edf3134db548
Create Date: 2019-08-22 03:21:01.367301

"""

# revision identifiers, used by Alembic.
revision = 'd4415b11be73'
down_revision = 'edf3134db548'

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sql_metrics', sa.Column('entity', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'sql_metrics', ['entity'])
    op.create_unique_constraint(None, 'table_columns', ['entity'])
    op.add_column('tables', sa.Column('entity', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'tables', ['entity'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='unique')
    op.drop_column('tables', 'entity')
    op.drop_constraint(None, 'table_columns', type_='unique')
    op.drop_constraint(None, 'sql_metrics', type_='unique')
    op.drop_column('sql_metrics', 'entity')
    # ### end Alembic commands ###
