export default {
  'anova': 'Analysis of Variance',
  'clean_data': 'Data Cleanse & Imputation',
  'plotly_tsne': 'Segmentation Analysis',
  'classification_prediction': 'Classification',
  'regression_prediction': 'Regression',
  'plotly_prediction': 'Time-series forecasting',
  'plotly_bubble': 'Bubble Chart',
  'plotly_correlation': 'Correlational Analysis',
  'bayesian_regression': 'Bayesian Linear Regression',
  'causal_inference': 'Causal Inference',
  'plotly_bar': 'Bar Chart',
  'line': 'Line Chart', 
  'filter_box': 'Filter Box',
  'histogram': 'Histogram',
  'table': 'Table',
  'box_plot': 'Box Plot',
  'sunburst': 'Sunburst Chart',
  'sankey': 'Sankey Diagram',
  'word_cloud': 'Word Cloud',
  'sentiment_analysis': 'Sentiment Analysis',
  'rose': 'Nightingale Rose Chart',
  'partition': 'Partition Chart',
  'event_flow': 'Event Flow',
  'directed_force': 'Force-directed Graph',
  'paired_ttest': 'Paired t-test Table',
  'chord': 'Chord Diagram',
  'pivot_table': 'Pivot Table',
  // sample superset
  'deck_path': 'Deck Path',
  'deck_arc': 'Deck Arc',
  'deck_geojson': 'Deck Geojson',
  'deck_grid': 'Deck Grid',
  'deck_hex': 'Deck Hex',
  'deck_multi': 'Deck Multi',
  'deck_path': 'Deck Path',
  'deck_polygon': 'Deck Polygon',
  'deck_scatter': 'Deck Scatter',
  'deck_screengrid': 'Deck Screengrid',
  'line_multi': 'Line Multi',
  'mapbox': 'Mapbox',
  'markup': 'Markup',
  'para': 'Para',
  'pie': 'Pie',
  'separator': 'Separator',
  'time_pivot': 'TimePivot',
  'time_table': 'TimeTable',
  'treemap': 'Treemap',
  'world_map': 'World Map',
  'area': 'Area',
  'bar': 'Bar',
  'big_number': 'Big Number',
  'big_number_total': 'Big Number Total',
  'bubble': 'Bubble',
  'bullet': 'Bullet',
  'cal_heatmap': 'Cal Heatmap',
  'compare': 'Compare',
  'country_map': 'Country Map',
  'dist_bar': 'Dist Bar',
  'dual_line': 'Dual Line',
  'heatmap': 'Heatmap',
  'horizon': 'Horizon',
  'iframe': 'Iframe',
}
